version: '3.8'

services:
  api:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/tinyurl_backend
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - db
  db:
    image: postgres:12.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tinyurl
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
  worker:
    build: .
    restart: always
    command: celery -A tinyurl_backend.worker.celery worker -l info -E
    volumes:
      - .:/tinyurl_backend
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - redis
volumes:
  postgres_data:
  redis_data:


